# Generated by Django 4.2 on 2023-04-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Good",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="Название")),
                (
                    "created",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата поступления"
                    ),
                ),
                ("price", models.FloatField(verbose_name="Цена")),
                (
                    "unit",
                    models.CharField(max_length=64, verbose_name="Единица измерения"),
                ),
                ("vendor", models.CharField(max_length=64, verbose_name="Поставщик")),
            ],
        ),
    ]
